export const brandingDoc = {
  "slug": [
    "branding"
  ],
  "title": "Babulus Branding Guidelines",
  "description": "Babulus Branding Guidelines",
  "category": "Reference",
  "html": "<h1 id=\"babulus-branding-guidelines\">Babulus Branding Guidelines</h1>\n<h2 id=\"core-philosophy\">Core Philosophy</h2>\n<p>Babulus is a professional-grade video production platform, not a toy app. Our aesthetic mimics high-end Non-Linear Editors (NLEs) like Adobe Premiere or DaVinci Resolve, combined with the clean precision of a modern IDE.</p>\n<p><strong>Key Vibe:</strong> \"Studio-Grade,\" \"Reliable,\" \"Scalable,\" \"Precision.\"</p>\n<h2 id=\"color--contrast-policy\">Color &amp; Contrast Policy</h2>\n<h3 id=\"softened-extremes\">Softened Extremes</h3>\n<p>To avoid jarring contrast and improve readability during long sessions:</p>\n<ul>\n<li><strong>Dark Mode Backgrounds:</strong> Never use pure black (<code>#000000</code>). Use deep grays (~25% lightness / Slate 3-4) to reduce eye strain.</li>\n<li><strong>Light Mode Text:</strong> Never use pure black text on white. Use deep grays (~75-80% black / Slate 11-12).</li>\n<li><strong>White Text:</strong> Avoid 100% white (<code>#FFFFFF</code>) on dark backgrounds. Use off-white (~90-95% / Slate 12 or Sand 12).</li>\n</ul>\n<h3 id=\"studio-ui-components\">Studio UI Components</h3>\n<p>When embedding \"Studio\" UI elements into marketing pages (e.g., screenshots, diagrams, example components):</p>\n<ul>\n<li>Use <strong>50% Gray</strong> backgrounds for the UI panels/chrome. This mimics the neutral gray workspace of professional video tools, which is designed to not interfere with color grading perception.</li>\n</ul>\n<h2 id=\"typography\">Typography</h2>\n<h3 id=\"weights--legibility\">Weights &amp; Legibility</h3>\n<p>Because we use lower contrast ratios (soft blacks/whites), we compensate with typography:</p>\n<ul>\n<li><strong>Heavier Weights:</strong> Prefer Medium (500) or Semibold (600) for body text where contrast is lower.</li>\n<li><strong>Fatter Fonts:</strong> Avoid thin/light fonts.</li>\n<li><strong>Structure:</strong> Use \"Eyebrows\" (uppercase, tracked out, small caps) above headlines to create hierarchy.</li>\n</ul>\n<h3 id=\"selected-font-pairing-impactful-studio\">Selected Font Pairing: \"Impactful Studio\"</h3>\n<ul>\n<li><strong>Headlines:</strong> Bebas Neue</li>\n<li><strong>Body:</strong> Montserrat</li>\n</ul>\n<p>These balance bold, cinematic impact (headlines) with modern geometric clarity (body), while staying legible at lower contrast.</p>\n<h2 id=\"layout\">Layout</h2>\n<ul>\n<li><strong>Public/Marketing:</strong> Standard scrolling web layout.</li>\n<li><strong>Studio/App:</strong> Fixed viewport, no scroll bounce (<code>overflow: hidden</code>), paned layout.</li>\n</ul>"
} as const;
